Repository petqua/frontend, pull requests merged in 2024-02, with the labels that each got.

#60 [#20] 수입입고 소식 미리보기 데이터 api 연동
  src/components/organisms/NewList.tsx
  src/pages/HomePage.tsx
Labels: 📬 API

#61 [#49] 검색 페이지 레이아웃 구현
  src/components/atoms/KeywordText.tsx
  src/components/atoms/index.ts
  src/components/molecules/RecentSearchList.tsx
  src/components/molecules/SearchBar.tsx
  src/components/molecules/TrendingKeywordList.tsx
  src/components/molecules/index.ts
  src/hooks/README.md
  src/hooks/index.ts
  src/hooks/useDebounce.tsx
  src/pages/Ex2Page.tsx
  src/states/SearchStore.ts
  src/states/index.ts
Labels: ✨ Feature, 🎨 Layout

#62 [#50] 검색 페이지 api 연동
  src/apis/axiosInstance.ts
  src/apis/index.ts
  src/apis/searchAPI.ts
  src/components/molecules/TrendingKeywordList.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/homeController.ts
  src/mocks/searchController.ts
  src/pages/HomePage.tsx
  src/pages/SearchPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ✨ Feature, 📬 API, 🎨 Layout

#63 Create pull_request_template.md
  .github/pull_request_template.md
Labels: 📃 Docs

#64 [#52] 상품 리스트 데이터 api 연동
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/apis/productAPI.ts
  src/components/molecules/FullScreen.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/molecules/RowScrollContainer.tsx
  src/components/organisms/NewList.tsx
  src/components/organisms/ProductList.tsx
  src/components/organisms/RecommendList.tsx
  src/interfaces/product.ts
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/MainPage.tsx
  src/pages/ProductListPage.tsx
  src/pages/SearchPage.tsx
  src/router.tsx
Labels: ✨ Feature, 📬 API

#68 [#66] 검색 상세 페이지 레이아웃 구현
  package-lock.json
  package.json
  src/components/atoms/Text.tsx
  src/components/molecules/Filter.tsx
  src/components/molecules/Modal.tsx
  src/components/molecules/RecentSearchList.tsx
  src/components/molecules/SearchBar.tsx
  src/components/molecules/TrendingKeywordList.tsx
  src/components/organisms/ProductList.tsx
  src/utils/format.ts
Labels: ✨ Feature, 🎨 Layout

#69 [#67] 검색 상세 페이지 api 연동
  src/apis/axiosInstance.ts
  src/apis/index.ts
  src/apis/searchAPI.ts
  src/components/molecules/SearchBar.tsx
  src/components/organisms/ProductList.tsx
  src/interfaces/product.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/searchController.ts
  src/pages/Ex1Page.tsx
  src/pages/MainPage.tsx
  src/pages/ProductListPage.tsx
  src/pages/SearchResultPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ✨ Feature, 📬 API, 🎨 Layout

#65 [#55] 찜 목록 레이아웃 구현
  public/icons/bubble-like-filled.svg
  public/icons/bubble-like.svg
  src/components/atoms/ProductImg.tsx
  src/components/molecules/ProductListItem.tsx
  src/interfaces/product.ts
  src/pages/WishListPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: 🎨 Layout

#70 [#56] 찜 목록 조회 api 연동
  src/apis/wishAPI.ts
  src/components/atoms/ProductImg.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/organisms/ProductList.tsx
  src/interfaces/product.ts
  src/pages/ProductListPage.tsx
  src/pages/WishListPage.tsx
  src/pages/index.ts
Labels: 📬 API, 🎨 Layout

#75 [#73] 로그인 페이지 레이아웃 구현
  .github/pull_request_template.md
  public/images/kakao_login_medium_wide.png
  public/images/login.png
  src/assets/logo-typo.svg
  src/components/molecules/FullScreen.tsx
  src/components/molecules/Modal.tsx
  src/components/organisms/ProductList.tsx
  src/pages/LoginPage.tsx
  src/pages/WishListPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ✨ Feature, 🎨 Layout, 🐞 Bug

#76 [#71] 상품 상세페이지 레이아웃 구현
  public/icons/bubble-like-gray.svg
  src/components/atoms/FlexBox.tsx
  src/components/atoms/ProductImg.tsx
  src/components/atoms/Text.tsx
  src/components/molecules/BlueButton.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/molecules/WhiteButton.tsx
  src/components/molecules/index.ts
  src/components/organisms/BottomPayBar.tsx
  src/components/organisms/ProductDetailContents.tsx
  src/components/organisms/ProductDetailData.tsx
  src/components/organisms/ProductDetailInfo.tsx
  src/components/organisms/index.ts
  src/pages/ProductDetailPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ✨ Feature, 🎨 Layout

#77 74 카카오 로그인 연동
  src/apis/AuthAPI.ts
  src/apis/axiosInstance.ts
  src/apis/index.ts
  src/apis/searchAPI.ts
  src/components/molecules/BottomNavBar.tsx
  src/pages/KakaoLoginPage.tsx
  src/pages/LoginPage.tsx
  src/pages/index.ts
  src/router.tsx
  src/states/AuthStore.ts
  src/states/index.ts
Labels: ✨ Feature, 📬 API

#80 [#72] 상품 상세페이지 조회 api 연동
  public/images/notice-ex.svg
  src/apis/index.ts
  src/apis/productAPI.ts
  src/components/molecules/ProductListItem.tsx
  src/components/molecules/StarRating.tsx
  src/components/molecules/index.ts
  src/components/organisms/BottomPayBar.tsx
  src/components/organisms/ProductDetailContents.tsx
  src/components/organisms/ProductDetailInfo.tsx
  src/components/organisms/ProductDetailMain.tsx
  src/components/organisms/index.ts
  src/interfaces/product.ts
  src/pages/ProductDetailPage.tsx
  src/router.tsx
Labels: ✨ Feature, 📬 API

#83 [#82] 연관상품 api 연동
  src/apis/productAPI.ts
  src/components/molecules/ProductListItem.tsx
  src/components/organisms/ProductDetailMain.tsx
  src/interfaces/product.ts
  src/pages/ProductDetailPage.tsx
Labels: 📬 API

#85 [#78] 배송지 form 레이아웃 구현
  src/components/molecules/AddressForm.tsx
  src/components/molecules/DeliveryRequestDropdown.tsx
  src/components/molecules/index.ts
  src/components/organisms/DeliveryAddressModal.tsx
  src/components/organisms/index.ts
  src/states/Ex1.ts
  src/states/PaymentStore.ts
  src/states/index.ts
Labels: ✨ Feature, 🎨 Layout

#91 [#90] 모달 리팩토링
  src/components/molecules/Modal.tsx
  src/components/molecules/index.ts
  src/components/organisms/index.ts
  src/components/organisms/modals/DeliveryAddressModal.tsx
  src/components/organisms/modals/ListModal.tsx
  src/components/organisms/modals/ReviewModal.tsx
  src/pages/ProductListPage.tsx
  src/pages/SearchResultPage.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Layout

#92 [#79] 배송지 form api 연동
  package-lock.json
  package.json
  src/apis/PaymentAPI.ts
  src/apis/axiosInstance.ts
  src/apis/index.ts
  src/components/molecules/AddressForm.tsx
  src/components/organisms/modals/DeliveryAddressModal.tsx
  src/interfaces/payment.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/paymentController.ts
  src/pages/PaymentPage.tsx
  src/pages/index.ts
  src/router.tsx
  src/states/PaymentStore.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#94 [#87] 후기 통계조회 api 연동
  src/apis/index.ts
  src/apis/reviewAPI.ts
  src/components/organisms/ReviewOverview.tsx
  src/interfaces/review.ts
  src/pages/ProductDetailPage.tsx
  src/pages/ProductListPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: 📬 API

#98 [#88] 후기 리스트 레이아웃 구현 api 연동
  src/apis/index.ts
  src/apis/reviewAPI.ts
  src/components/atoms/ProfileImg.tsx
  src/components/atoms/index.ts
  src/components/molecules/BlueButton.tsx
  src/components/molecules/Filter.tsx
  src/components/molecules/ReviewItem.tsx
  src/components/molecules/WhiteButton.tsx
  src/components/molecules/index.ts
  src/components/organisms/ReviewList.tsx
  src/components/organisms/index.ts
  src/components/organisms/modals/ReviewModal.tsx
  src/interfaces/review.ts
  src/pages/ProductDetailPage.tsx
  src/pages/ReviewPage.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/utils/format.ts
Labels: ✨ Feature, 📬 API, 🎨 Layout

#99 [#96] 결제 어종 정보 api 연동
  src/apis/PaymentAPI.ts
  src/apis/cartAPI.ts
  src/apis/index.ts
  src/components/molecules/CartFish.tsx
  src/components/organisms/CartFishList.tsx
  src/mocks/handlers.ts
  src/mocks/paymentController.ts
  src/pages/PaymentPage.tsx
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#105 hotfix-[#104] 파일명 변경
  src/apis/authAPI.ts
  src/apis/paymentAPI.ts
Labels: 🐞 Bug

#101 [#84] 찜하기 api 연동
  src/apis/PaymentAPI.ts
  src/apis/axiosInstance.ts
  src/apis/index.ts
  src/apis/wishAPI.ts
  src/components/atoms/ProductImg.tsx
  src/components/molecules/Modal.tsx
  src/components/molecules/PopUp.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/molecules/TopNav.tsx
  src/components/molecules/index.ts
  src/components/organisms/BottomPayBar.tsx
  src/interfaces/product.ts
  src/pages/ProductListPage.tsx
  src/pages/WishListPage.tsx
  src/states/PopUpStore.ts
  src/states/index.ts
  src/styles/keyframes.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 🎨 Layout

#107 [#102] 봉달목록 페이지 레이아웃 구현
  src/apis/paymentAPI.ts
  src/components/atoms/FlexBox.tsx
  src/components/molecules/CartItem.tsx
  src/components/molecules/Confirm.tsx
  src/components/molecules/index.ts
  src/components/organisms/CartList.tsx
  src/components/organisms/index.ts
  src/components/organisms/modals/OptionModal.tsx
  src/pages/CartPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ✨ Feature, 🎨 Layout

#109 [#108] 상품 후기 추천 api 연동
  src/apis/index.ts
  src/apis/reviewAPI.ts
  src/components/molecules/ReviewItem.tsx
  src/components/organisms/ReviewList.tsx
Labels: 📬 API

#112 [#110] 탑 네비바 디자인 수정
  src/components/molecules/TopNav.tsx
  src/pages/HomePage.tsx
Labels: 🔨 Refactor, 🎨 Layout

#111 [#81] 상품 상세페이지 이미지 캐러샐 제작
  src/apis/productAPI.ts
  src/components/atoms/ProductImg.tsx
  src/components/molecules/Carousel.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/molecules/ReviewItem.tsx
  src/components/organisms/ImageDetail.tsx
  src/components/organisms/ProductDetailMain.tsx
  src/components/organisms/index.ts
  src/interfaces/carousel.ts
  src/interfaces/product.ts
  src/pages/HomePage.tsx
  src/pages/ProductDetailPage.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Layout

#114 [#113] 결제 정보 컴포넌트 구현
  src/components/molecules/PaymentInfo.tsx
  src/components/molecules/index.ts
  src/pages/PaymentPage.tsx
Labels: ✨ Feature, 🎨 Layout

#118 [#115] 결제 어종 정보 수정사항 반영
  src/components/molecules/CartFish.tsx
  src/components/organisms/CartFishList.tsx
  src/components/organisms/CartFishListByStoreName.tsx
  src/components/organisms/index.ts
  src/interfaces/payment.ts
  src/mocks/paymentController.ts
  src/pages/PaymentPage.tsx
  src/router.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/utils/payment.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Layout

#120 [#119] 결제 금액 컴포넌트 구현
  src/components/atoms/CustomHr.tsx
  src/components/molecules/CartFish.tsx
  src/components/molecules/PaymentInfo.tsx
  src/components/molecules/PaymentSummary.tsx
  src/components/molecules/index.ts
  src/components/organisms/CartFishList.tsx
  src/components/organisms/CartFishListByStoreName.tsx
  src/interfaces/payment.ts
  src/pages/PaymentPage.tsx
  src/utils/delivery.ts
Labels: ✨ Feature, 🎨 Layout
