Repository petqua/frontend, pull requests merged in 2024-05, with the labels that each got.

#132 [#131] 아이콘 라이브러리 변경
  package-lock.json
  package.json
  src/components/atoms/Checkbox.tsx
  src/components/atoms/Icon.tsx
  src/components/molecules/BottomNavBar.tsx
  src/components/molecules/Carousel.tsx
  src/components/molecules/CartItem.tsx
  src/components/molecules/DeliveryRequestDropdown.tsx
  src/components/molecules/Filter.tsx
  src/components/molecules/Modal.tsx
  src/components/molecules/PaymentSummary.tsx
  src/components/molecules/RecentSearchList.tsx
  src/components/molecules/ReviewItem.tsx
  src/components/molecules/SearchBar.tsx
  src/components/molecules/StarRating.tsx
  src/components/molecules/TopNav.tsx
  src/components/molecules/TrendingKeywordList.tsx
  src/components/molecules/WhiteButton.tsx
  src/components/organisms/CartList.tsx
  src/components/organisms/ImageDetail.tsx
  src/components/organisms/ProductDetailMain.tsx
  src/components/organisms/ReviewList.tsx
  src/components/organisms/modals/ListModal.tsx
  src/components/organisms/modals/OptionModal.tsx
  src/components/organisms/modals/SpeciesModal.tsx
  src/pages/ProductDetailPage.tsx
Labels: 🔨 Refactor, 🎨 Layout

#134 [#130] 마이페이지 레이아웃 구현
  public/icons/option.svg
  src/components/atoms/CustomHr.tsx
  src/components/atoms/MethodTag.tsx
  src/components/atoms/index.ts
  src/components/molecules/CartItem.tsx
  src/components/molecules/Confirm.tsx
  src/components/molecules/MenuItem.tsx
  src/components/molecules/TopNav.tsx
  src/components/molecules/index.ts
  src/components/organisms/CartList.tsx
  src/components/organisms/TotalPayInfo.tsx
  src/components/organisms/index.ts
  src/pages/MyPage.tsx
  src/pages/OptionPage.tsx
  src/pages/OrderDetailPage.tsx
  src/pages/OrderListPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: 🔨 Refactor, 🎨 Layout

#136 [#135] 페이지 컴포넌트 코드 스플리팅
  src/App.tsx
  src/router.tsx
Labels: 🔨 Refactor

#138 [#137] 검색 페이지 스켈레톤 스크린 구현
  src/components/organisms/SkeletonProductList.tsx
  src/components/organisms/index.ts
  src/pages/SearchResultPage.tsx
Labels: ✨ Feature
