Repository petqua/frontend, pull requests merged in 2024-01, with the labels that each got.

#22 [#11] eslint / prettier 설정
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  tsconfig.json
  vite.config.ts
Labels: ⚙ Setting

#25 [#13] 통신 설정
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/apis/README.md
  src/apis/axiosInstance.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
Labels: ⚙ Setting

#26 [#12] 스타일 설정
  package-lock.json
  package.json
  src/App.tsx
  src/pages/Ex1Page.tsx
  src/pages/Ex2Page.tsx
  src/pages/MainPage.tsx
  src/pages/index.ts
  src/router.tsx
  src/styles/GlobalStyles.ts
  src/styles/README.md
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: ⚙ Setting

#27 [#14] 상태 관리 설정
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/pages/Ex1Page.tsx
  src/pages/README.md
  src/states/Ex1.ts
  src/states/README.md
Labels: ⚙ Setting

#34 [#16] 상품 아이템 컴포넌트 구현
  public/icons/bubble-like-filled.svg
  public/icons/vite.svg
  public/images/product-item-ex.svg
  public/images/vite.svg
  src/components/atoms/ProductImg.tsx
  src/components/atoms/README.md
  src/components/atoms/Text.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/molecules/README.md
  src/pages/MainPage.tsx
Labels: 🎨 Layout

#36 [#33] Full Screen 컴포넌트 구현
  .eslintrc.cjs
  src/components/molecules/FullScreen.tsx
Labels: 🎨 Layout

#35 [#17] 대표 상품 아이템 컴포넌트 구현
  src/components/atoms/FlexBox.tsx
  src/components/atoms/ProductImg.tsx
  src/components/atoms/Text.tsx
  src/components/atoms/index.ts
  src/components/molecules/ProductListItem.tsx
  src/components/molecules/index.ts
  src/pages/MainPage.tsx
  src/styles/theme.ts
Labels: 🎨 Layout

#38 [#31] 공지 레이아웃 구현
  src/components/molecules/Notification.tsx
  src/components/molecules/index.ts
  src/styles/styled.d.ts
Labels: 🎨 Layout

#37 [#32] 카테고리 리스트 레이아웃 구현
  index.html
  public/icons/category/1.svg
  public/icons/category/2.svg
  public/icons/category/3.svg
  public/icons/category/4.svg
  public/icons/category/5.svg
  public/icons/category/6.svg
  public/icons/category/7.svg
  public/icons/category/8.svg
  src/components/atoms/CategoryImg.tsx
  src/components/molecules/CategoryItem.tsx
  src/components/molecules/index.ts
  src/components/organisms/CategoryList.tsx
  src/components/organisms/README.md
  src/components/organisms/index.ts
  src/styles/GlobalStyles.ts
Labels: ✨ Feature, 🎨 Layout

#40 [#19] 펫쿠아 강력추천 미리보기 레이아웃 구현
  src/components/atoms/FlexBox.tsx
  src/components/molecules/PreviewListTitle.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/molecules/RowScrollContainer.tsx
  src/components/molecules/index.ts
  src/components/organisms/RecommendList.tsx
  src/components/organisms/index.ts
  src/pages/HomePage.tsx
  src/pages/MainPage.tsx
Labels: 🎨 Layout

#43 [#29] 배너 이미지 api 연동
  .gitignore
  package-lock.json
  package.json
  src/apis/axiosInstance.ts
  src/apis/homeAPI.ts
  src/apis/index.ts
  src/components/atoms/Text.tsx
  src/components/molecules/Carousel.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/HomePage.tsx
  vite.config.ts
Labels: 📬 API, 🐞 Bug

#44 [#23] 필터링 컴포넌트 구현
  src/components/molecules/Filter.tsx
  src/components/molecules/Modal.tsx
  src/components/molecules/index.ts
  src/pages/ProductListPage.tsx
  src/pages/index.ts
  src/router.tsx
  src/utils/format.ts
Labels: 🎨 Layout

#45 [#30] 공지 내용 api 연동
  src/apis/axiosInstance.ts
  src/apis/homeAPI.ts
  src/apis/index.ts
  src/components/molecules/Notification.tsx
  src/pages/HomePage.tsx
  vite.config.ts
Labels: ⚙ Setting, 📬 API

#47 [#46] 홈페이지 리팩토링
  src/components/molecules/Carousel.tsx
  src/components/molecules/FullScreen.tsx
  src/components/organisms/CategoryList.tsx
  src/pages/HomePage.tsx
  src/router.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: 🔨 Refactor, 🎨 Layout

#51 [#42] 상품 리스트 레이아웃 구현
  src/components/atoms/FlexBox.tsx
  src/components/molecules/Modal.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/organisms/ProductList.tsx
  src/components/organisms/index.ts
  src/interfaces/README.md
  src/interfaces/product.ts
  src/pages/ProductListPage.tsx
  src/utils/README.md
Labels: 🎨 Layout

#58 [#48] 하단 네비바 레이아웃 구현
  package-lock.json
  package.json
  src/App.css
  src/assets/chat.svg
  src/assets/double-fish.svg
  src/components/molecules/BottomNavBar.tsx
  src/components/molecules/Carousel.tsx
  src/components/molecules/FullScreen.tsx
  src/components/molecules/Notification.tsx
  src/components/molecules/index.ts
  src/pages/HomePage.tsx
  src/styles/GlobalStyles.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: 🔨 Refactor, 🎨 Layout

#57 [#54] 상단 네비바 레이아웃 구현
  public/icons/alarm.svg
  public/icons/basket.svg
  public/icons/bubble-like.svg
  public/icons/logo-typo.svg
  src/components/molecules/TopNav.tsx
  src/components/molecules/index.ts
  src/pages/HomePage.tsx
  src/pages/ProductListPage.tsx
  src/styles/GlobalStyles.ts
Labels: 🎨 Layout

#59 [#18] 펫쿠아 강력추천 미리보기 데이터 api 연동
  src/apis/index.ts
  src/apis/productAPI.ts
  src/components/atoms/ProductImg.tsx
  src/components/molecules/Filter.tsx
  src/components/molecules/ProductListItem.tsx
  src/components/organisms/RecommendList.tsx
  src/interfaces/product.ts
  src/pages/HomePage.tsx
Labels: 📬 API
